INSERT INTO `pops-204909.KIDS.POPS_Kids_basic` 

(
  CMS_ID ,
  DATE,
  CHANNEL_ID,
  VIDEO_ID,
  EST_VIEWS,
  EST_REVENUE
)
SELECT * FROM `pops-204909.KIDS.Doraemon` WHERE CHANNEL_ID= 'UC1psboQLDVCEOD46RNPZdgg'